#!/usr/bin/env python3
"""Calibration token set for the calibrated-NVFP4-scales step of Crow #300 (phase 2, "Local-Hessian").

Binding spec: decode_out/p2-lh/PREREG.md, section "Calibration data". Deterministic: one
numpy.random.default_rng(0), drawn in the fixed order agent -> code -> vault -> docs.

Usage (oracle venv, CPU only, from anywhere):
  CUDA_VISIBLE_DEVICES="" .venv-oracle/bin/python tools/calib_qwen35_ids.py [--out-dir DIR]

Writes DIR/calib-ids.json and DIR/calib-manifest.md (default DIR = decode_out/p2-lh).

Sources and shares (224 x 2048 + 4 x 8192 = 491,520 tokens):
- agent: the five Crow session files under decode_out/sessions/, each rendered through the 27B's
  chat template (tokenize=False, then tokenized with add_special_tokens=False) into one stream.
  96 x 2048 + 4 x 8192, allocated to the sessions by largest remainder on their token counts.
- code: crow-nest engine/src/**/*.rs, converter/src/**/*.rs and Crow cli/*.py, sorted by path,
  each file prefixed with a `// file: <path>` line, tokenized per file, ids concatenated. 64 x 2048.
- notes-vault: Obsidian vault **/*.md minus generated files (INDEX - *.md, */01_Issues/* written by
  06_tools/sync_issues.py, _templates/*, dot directories). 32 x 2048.
- notes-docs: crow-nest docs/*.md (top level, as the PREREG glob says). 32 x 2048.
Windows inside one stream are non-overlapping: a random order of the window lengths, then k sorted
uniform gaps in [0, N - sum(len)], start_i = gap_i + sum of the lengths before it.

Session normalisation (the same as tools/session_ids.py and tools/replay-session.py):
- image_url parts of list contents are dropped, text parts joined (calibration is text-only; the
  template would otherwise emit a bare <|image_pad|> with no vision embedding behind it);
- tool_calls arguments stored as JSON strings are parsed to dicts (the template iterates them with
  |items); a string that is not a JSON object becomes {"raw": <string>};
- tools=None: the session files store no tool schemas (Crow sends them per request).
Template defaults are kept: enable_thinking / reasoning_effort unset (the "xhigh" system line),
preserve_thinking unset (every stored reasoning_content is rendered).

Held-out guard: no chosen window may contain an exact 64-token substring of the evaluation id sets
(oracle-tf298, oracle-t2b, oracle-en) -- asserted. A second guard does the same against the
excluded-by-rule material: the libghost long-context id sets (decode_out/oracle-longctx/*-ids.json,
generated by tools/longctx-gate.py) and the five books tools/corpora/*.txt -- also asserted.
"""
import argparse
import glob
import hashlib
import json
import os
import sys

import numpy as np

HOME = os.path.expanduser("~")
ROOT = os.path.join(HOME, "Projects", "crow-nest")
PROJECTS = os.path.join(HOME, "Projects")
MODEL = os.path.join(ROOT, "models", "Qwen3.8-27B")
SESS = os.path.join(ROOT, "decode_out", "sessions")
SESSIONS = [
    "2026-09-17-goalmode/crow-session/session.json",
    "2026-09-22-diorama-rollover/session.json",
    "2026-09-23-diorama/seg1-rollover-20260923-073002.json",
    "2026-09-23-diorama/seg2-rollover-20260923-082406.json",
    "2026-09-23-diorama/seg3-session.json",
]
VAULT = os.path.join(PROJECTS, "Obsidian-Vault")
CROW = os.path.join(PROJECTS, "crow")
SEED = 0
W = 2048
WL = 8192
N_AGENT, N_AGENT_LONG, N_CODE, N_VAULT, N_DOCS = 96, 4, 64, 32, 32
NGRAM = 64
EVAL_SETS = ["decode_out/oracle-tf298/tf298-ids.json", "decode_out/oracle-t2b/t2b-tf-ids.json"] + \
    sorted(os.path.relpath(p, ROOT) for p in glob.glob(os.path.join(ROOT, "decode_out/oracle-en/en-prose-*-ids.json")))


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def rel(path):
    return os.path.relpath(path, PROJECTS)


# ---------------------------------------------------------------- sessions

def normalize(raw, stats):
    out = []
    for m in raw:
        msg = {"role": m["role"]}
        c = m.get("content")
        if isinstance(c, list):
            imgs = [p for p in c if p.get("type") != "text"]
            stats["image_parts_dropped"] += len(imgs)
            stats["list_contents_joined"] += 1
            c = "".join(p.get("text", "") for p in c if p.get("type") == "text")
        msg["content"] = c if c is not None else ""
        if m.get("reasoning_content"):
            msg["reasoning_content"] = m["reasoning_content"]
        calls = m.get("tool_calls")
        if isinstance(calls, str):
            calls = json.loads(calls)
        if calls:
            msg["tool_calls"] = []
            for tc in calls:
                fn = dict(tc.get("function") or tc)
                args = fn.get("arguments")
                if isinstance(args, str):
                    try:
                        parsed = json.loads(args) if args.strip() else {}
                    except ValueError:
                        parsed = None
                    if isinstance(parsed, dict):
                        args = parsed
                        stats["args_parsed"] += 1
                    else:
                        args = {"raw": args}
                        stats["args_raw_wrapped"] += 1
                elif args is None:
                    args = {}
                msg["tool_calls"].append({"type": "function", "function": {
                    "name": fn.get("name", ""), "arguments": args}})
        if m.get("tool_call_id"):
            msg["tool_call_id"] = m["tool_call_id"]
        out.append(msg)
    return out


def session_stream(tok, relpath):
    path = os.path.join(SESS, relpath)
    doc = json.load(open(path, encoding="utf-8"))
    assert "tools" not in doc, "session stores tool schemas; pass them"
    stats = {"messages": len(doc["messages"]), "image_parts_dropped": 0, "list_contents_joined": 0,
             "args_parsed": 0, "args_raw_wrapped": 0}
    msgs = normalize(doc["messages"], stats)
    text = tok.apply_chat_template(msgs, tools=None, tokenize=False)
    ids = tok(text, add_special_tokens=False)["input_ids"]
    return np.asarray(ids, dtype=np.int64), stats, path


# ---------------------------------------------------------------- plain text

def text_stream(tok, paths, header):
    """per-file tokenization, ids concatenated; returns ids and the file start offsets"""
    parts, starts, names, pos = [], [], [], 0
    for p in paths:
        body = open(p, encoding="utf-8", errors="replace").read()
        text = (f"// file: {rel(p)}\n" + body + "\n") if header else (body.rstrip("\n") + "\n\n")
        ids = tok(text, add_special_tokens=False)["input_ids"]
        parts.append(np.asarray(ids, dtype=np.int64))
        starts.append(pos)
        names.append(rel(p))
        pos += len(ids)
    return np.concatenate(parts), np.asarray(starts), names


def code_files():
    fs = glob.glob(os.path.join(ROOT, "engine/src/**/*.rs"), recursive=True)
    fs += glob.glob(os.path.join(ROOT, "converter/src/**/*.rs"), recursive=True)
    fs += glob.glob(os.path.join(CROW, "cli/*.py"))
    return sorted(fs, key=rel)


def vault_files():
    keep, skipped = [], {"INDEX - *.md (generated by 06_tools/build_index.py)": 0,
                         "*/01_Issues/* (generated by 06_tools/sync_issues.py)": 0,
                         "_templates/* (note templates)": 0}
    for dp, dns, fns in os.walk(VAULT):
        dns[:] = sorted(d for d in dns if not d.startswith("."))
        for fn in sorted(fns):
            if not fn.endswith(".md"):
                continue
            p = os.path.join(dp, fn)
            r = os.path.relpath(p, VAULT)
            if r.split(os.sep)[0] == "_templates":
                skipped["_templates/* (note templates)"] += 1
            elif "01_Issues" in r.split(os.sep):
                skipped["*/01_Issues/* (generated by 06_tools/sync_issues.py)"] += 1
            elif fn.startswith("INDEX - "):
                skipped["INDEX - *.md (generated by 06_tools/build_index.py)"] += 1
            else:
                keep.append(p)
    return sorted(keep, key=rel), skipped


def docs_files():
    return sorted(glob.glob(os.path.join(ROOT, "docs/*.md")), key=rel)


# ---------------------------------------------------------------- windows

def place(rng, n, lengths):
    """non-overlapping windows of the given lengths in a stream of n tokens -> sorted (start, len)"""
    lens = [lengths[i] for i in rng.permutation(len(lengths))]
    slack = n - sum(lens)
    if slack < 0:
        raise SystemExit(f"stream of {n} tokens cannot hold {len(lens)} windows totalling {sum(lens)}")
    gaps = np.sort(rng.integers(0, slack + 1, size=len(lens)))
    out, before = [], 0
    for g, L in zip(gaps, lens):
        out.append((int(g) + before, L))
        before += L
    return out


def largest_remainder(total, weights):
    w = np.asarray(weights, dtype=np.float64)
    q = total * w / w.sum()
    base = np.floor(q).astype(int)
    rest = total - base.sum()
    order = sorted(range(len(w)), key=lambda i: (-(q[i] - base[i]), i))
    for i in order[:rest]:
        base[i] += 1
    return [int(x) for x in base]


def files_of(starts, names, a, b):
    i0 = int(np.searchsorted(starts, a, side="right")) - 1
    i1 = int(np.searchsorted(starts, b - 1, side="right")) - 1
    return names[i0:i1 + 1]


# ---------------------------------------------------------------- 64-gram guard

P = np.uint64(0x9E3779B97F4A7C15)


def ngram_hashes(ids):
    a = np.asarray(ids, dtype=np.uint64)
    n = len(a) - NGRAM + 1
    if n <= 0:
        return np.zeros(0, dtype=np.uint64)
    h = np.zeros(n, dtype=np.uint64)
    with np.errstate(over="ignore"):
        for j in range(NGRAM):
            h = h * P + (a[j:j + n] + np.uint64(1))
    return h


class Guard:
    def __init__(self, name):
        self.name, self.seqs, self.hashes = name, [], []

    def add(self, label, ids):
        ids = np.asarray(ids, dtype=np.int64)
        self.seqs.append((label, ids))
        self.hashes.append(ngram_hashes(ids))

    def freeze(self):
        self.all = np.unique(np.concatenate(self.hashes)) if self.hashes else np.zeros(0, np.uint64)
        return len(self.all)

    def hits(self, ids):
        h = ngram_hashes(ids)
        idx = np.nonzero(np.isin(h, self.all))[0]
        found = []
        for i in idx:  # verify exactly, a hash match is only a candidate
            g = np.asarray(ids[i:i + NGRAM], dtype=np.int64)
            for label, seq in self.seqs:
                sh = ngram_hashes(seq)
                for j in np.nonzero(sh == h[i])[0]:
                    if np.array_equal(seq[j:j + NGRAM], g):
                        found.append((int(i), label, int(j)))
        return found


# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-dir", default=os.path.join(ROOT, "decode_out", "p2-lh"))
    a = ap.parse_args()
    if os.environ.get("CUDA_VISIBLE_DEVICES", None) != "":
        raise SystemExit('run with CUDA_VISIBLE_DEVICES="" (CPU only)')

    import transformers
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained(MODEL)
    rng = np.random.default_rng(SEED)
    windows, shas, report = [], {}, {}

    # agent traffic
    streams = []
    for r in SESSIONS:
        ids, stats, path = session_stream(tok, r)
        shas[rel(path)] = sha256(path)
        streams.append((rel(path), ids, stats))
        print(f"agent  {r}: {len(ids)} tokens {stats}", file=sys.stderr)
    counts = [len(s[1]) for s in streams]
    n_short = largest_remainder(N_AGENT, counts)
    n_long = largest_remainder(N_AGENT_LONG, counts)
    report["agent"] = []
    for (name, ids, stats), ks, kl in zip(streams, n_short, n_long):
        for start, L in place(rng, len(ids), [W] * ks + [WL] * kl):
            windows.append({"source": "agent", "file_or_session": name, "start": start, "len": L,
                            "ids": ids[start:start + L]})
        report["agent"].append((name, len(ids), ks, kl, stats))

    # code, vault, docs
    vfiles, vskipped = vault_files()
    for src, files, k, header in (("code", code_files(), N_CODE, True),
                                  ("notes-vault", vfiles, N_VAULT, False),
                                  ("notes-docs", docs_files(), N_DOCS, False)):
        for p in files:
            shas[rel(p)] = sha256(p)
        ids, starts, names = text_stream(tok, files, header)
        print(f"{src}: {len(files)} files, {len(ids)} tokens", file=sys.stderr)
        report[src] = (len(files), len(ids))
        for start, L in place(rng, len(ids), [W] * k):
            fs = files_of(starts, names, start, start + L)
            w = {"source": src, "file_or_session": fs[0], "start": start, "len": L,
                 "ids": ids[start:start + L]}
            if len(fs) > 1:
                w["files"] = fs
            windows.append(w)

    # guards
    ev = Guard("eval")
    for r in EVAL_SETS:
        ev.add(r, json.load(open(os.path.join(ROOT, r))))
    n_ev = ev.freeze()
    ex = Guard("excluded")
    ex_sources = sorted(glob.glob(os.path.join(ROOT, "decode_out/oracle-longctx/*-ids.json")))
    for p in ex_sources:
        ex.add(os.path.relpath(p, ROOT), json.load(open(p)))
    books = sorted(p for p in glob.glob(os.path.join(ROOT, "tools/corpora/*.txt")) if not p.endswith(".raw.txt"))
    for p in books:
        ex.add(os.path.relpath(p, ROOT), tok(open(p, encoding="utf-8").read(), add_special_tokens=False)["input_ids"])
    n_ex = ex.freeze()
    ev_hits = [(i, h) for i, w in enumerate(windows) for h in ev.hits(w["ids"])]
    ex_hits = [(i, h) for i, w in enumerate(windows) for h in ex.hits(w["ids"])]

    # totals
    total = sum(w["len"] for w in windows)
    n2k = sum(1 for w in windows if w["len"] == W)
    n8k = sum(1 for w in windows if w["len"] == WL)
    assert (n2k, n8k, total) == (224, 4, 491520), (n2k, n8k, total)
    for w in windows:
        assert len(w["ids"]) == w["len"]
    by = {}
    for w in windows:
        by.setdefault((w["source"], w["file_or_session"] if w["source"] == "agent" else ""), []).append(w)
    for ws in by.values():  # non-overlap inside every stream
        iv = sorted((w["start"], w["start"] + w["len"]) for w in ws)
        assert all(b0 >= a1 for (_, a1), (b0, _) in zip(iv, iv[1:]))
    assert not ev_hits, f"eval overlap: {ev_hits[:5]}"
    assert not ex_hits, f"excluded-material overlap: {ex_hits[:5]}"

    tokfiles = {f: sha256(os.path.join(MODEL, f)) for f in ("tokenizer.json", "tokenizer_config.json", "chat_template.jinja")}
    out = {"prereg": "decode_out/p2-lh/PREREG.md#calibration-data",
           "builder": "tools/calib_qwen35_ids.py",
           "windows": [dict(w, ids=[int(x) for x in w["ids"]]) for w in windows],
           "total_tokens": total, "seed": SEED,
           "tokenizer": {"path": os.path.relpath(MODEL, ROOT), "class": type(tok).__name__,
                         "transformers": transformers.__version__, "sha256": tokfiles},
           "sha256_of_sources": shas,
           "overlap_check": {"ngram": NGRAM, "eval_sets": EVAL_SETS, "eval_ngrams": n_ev, "eval_hits": 0,
                             "excluded_sets": [os.path.relpath(p, ROOT) for p in ex_sources + books],
                             "excluded_ngrams": n_ex, "excluded_hits": 0}}
    os.makedirs(a.out_dir, exist_ok=True)
    jpath = os.path.join(a.out_dir, "calib-ids.json")
    with open(jpath, "w") as f:
        json.dump(out, f, separators=(",", ":"))
    ids_sha = hashlib.sha256(np.concatenate([w["ids"] for w in windows]).astype("<i4").tobytes()).hexdigest()

    # manifest
    L = ["# Calibration token set (Crow #300 phase 2, Local-Hessian)", "",
         "Built by `tools/calib_qwen35_ids.py` per `decode_out/p2-lh/PREREG.md` (section \"Calibration data\").",
         f"Seed {SEED} (`numpy.random.default_rng`), tokenizer `models/Qwen3.8-27B` ({type(tok).__name__}, "
         f"transformers {transformers.__version__}). sha256 of all window ids as int32 LE, in file order: `{ids_sha}`.", "",
         "## Windows", "",
         "| source | stream | stream tokens | 2048 windows | 8192 windows | tokens taken |", "|---|---|---:|---:|---:|---:|"]
    for name, n, ks, kl, _ in report["agent"]:
        L.append(f"| agent | `{name}` | {n:,} | {ks} | {kl} | {ks * W + kl * WL:,} |")
    for src in ("code", "notes-vault", "notes-docs"):
        nf, n = report[src]
        k = {"code": N_CODE, "notes-vault": N_VAULT, "notes-docs": N_DOCS}[src]
        L.append(f"| {src} | {nf} files | {n:,} | {k} | 0 | {k * W:,} |")
    L += [f"| **total** | | | **{n2k}** | **{n8k}** | **{total:,}** |", ""]
    code_py = sum(1 for w in windows if w["source"] == "code" and w["file_or_session"].endswith(".py"))
    L += [f"Code windows by the file they start in: {N_CODE - code_py} Rust, {code_py} Python "
          "(one stream, positions uniform over it; no language split is prescribed).", "",
          "## Rendering and normalisation", "",
          "- Sessions: `apply_chat_template(messages, tools=None, tokenize=False)` with the 27B's own template, then "
          "`tokenizer(text, add_special_tokens=False)`; one stream per session file. Template defaults kept "
          "(enable_thinking/reasoning_effort unset -> the \"xhigh\" system line; preserve_thinking unset -> every stored "
          "`reasoning_content` rendered).",
          "- No tool schemas: the session files store none (Crow sends them per request); same choice as "
          "`tools/session_ids.py`. The template therefore renders no `# Tools` block; assistant tool calls are "
          "rendered in its `<tool_call><function=...>` form.",
          "- `image_url` parts dropped, text parts joined (text-only calibration; a bare `<|image_pad|>` would have "
          "no vision embedding behind it). `tool_calls[].function.arguments` JSON strings parsed to dicts (the template "
          "needs `|items`); non-object strings wrapped as `{\"raw\": ...}`.", "",
          "| session | messages | list contents joined | image parts dropped | args parsed | args wrapped raw |",
          "|---|---:|---:|---:|---:|---:|"]
    for name, _, _, _, s in report["agent"]:
        L.append(f"| `{name}` | {s['messages']} | {s['list_contents_joined']} | {s['image_parts_dropped']} | "
                 f"{s['args_parsed']} | {s['args_raw_wrapped']} |")
    L += ["", "- Code: files sorted by path (relative to ~/Projects), each prefixed `// file: <path>`, tokenized per "
          "file (add_special_tokens=False), ids concatenated. Crow `cli/*.py` taken as globbed, test_*.py included; "
          "enough tokens, so no wider Crow glob was needed.",
          "- Notes: markdown tokenized per file (add_special_tokens=False), files separated by a blank line, no header. "
          "crow-nest docs = top-level `docs/*.md` only (PREREG glob; `docs/acceptance/`, `docs/archive/` not included).",
          "", "## Skipped in the vault", ""]
    for k2, v in vskipped.items():
        L.append(f"- {v} files: {k2}")
    L += ["- dot directories (`.git`, `.obsidian`), non-markdown files", "",
          "## Held-out check", "",
          f"- Eval sets ({', '.join('`' + e + '`' for e in EVAL_SETS)}): {n_ev:,} distinct {NGRAM}-grams; "
          f"windows containing one: **{len(ev_hits)}**.",
          f"- Excluded-by-rule material (libghost id sets `decode_out/oracle-longctx/*-ids.json`, the five books "
          f"`tools/corpora/*.txt`): {n_ex:,} distinct {NGRAM}-grams; windows containing one: **{len(ex_hits)}**.",
          "- Sources never read: `tools/corpora/*` as calibration text, `decode_out/oracle-*` id sets, "
          "`tools/longctx-gate.py` output.", ""]
    with open(os.path.join(a.out_dir, "calib-manifest.md"), "w") as f:
        f.write("\n".join(L))
    print(f"wrote {jpath}: {len(windows)} windows, {total} tokens, ids sha256 {ids_sha}; "
          f"eval hits {len(ev_hits)}, excluded hits {len(ex_hits)}", file=sys.stderr)


if __name__ == "__main__":
    main()
